wildfly:
 rules:
   - id: asd
     titleBody: "asd"
     directories:
       - asd
     notify: [hdhfghfghfghfgh]
   - id: foo
     titleBody: "foo"
     directories:
       - foo
     notify: [hdhfghfghfghfgh, fgdjkfgdjklfgdklfgdklfgdkl]
 format:
   title-check:
     pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
     message: "Wrong content of the title!"
   description:
     regexes:
        - pattern: "JIRA:\\s+https://issues.redhat.com/browse/WFLY-\\d+|https://issues.redhat.com/browse/WFLY-\\d+"
          message: "The PR description must contain a link to the JIRA issue"
   commits-quantity:
     quantity: "1-3"
     message: "Too many commits in PR!"
